name: Deploy to GitHub Pages (gh-pages)

# This workflow avoids the Pages artifact actions which can depend on
# deprecated action versions. It builds a static site from `docs/` and
# pushes directly to the `gh-pages` branch, then configures Pages to
# publish from that branch via the REST API.
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare site (copy docs -> site)
        run: |
          rm -rf site
          mkdir -p site
          cp -r docs/* site/ || true
          # Ensure Jekyll does not process the site when deployed to Pages
          touch site/.nojekyll

      - name: Deploy to gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -e
          cd site
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          if git diff --cached --quiet; then
            echo "No changes to deploy"
            exit 0
          fi
          git commit -m "Deploy docs to gh-pages: ${GITHUB_SHA}"
          git branch -M gh-pages
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git"
          git push --force origin gh-pages

      - name: Configure Pages to publish from gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          # Ensure the repository is configured to publish from gh-pages (root)
          curl -X PUT -H "Authorization: Bearer ${GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${REPO}/pages" \
            -d '{"source":{"branch":"gh-pages","path":"/"}}'
